# Generated by Django 5.2.5 on 2025-08-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_fundraiser_owner_pledge_supporter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundraiser',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
