# Generated by Django 5.1 on 2025-09-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0003_rename_date_create_fundraiser_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
